# Generated by Django 5.0.7 on 2024-07-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='status',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='trigger_price',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='user',
        ),
        migrations.AddField(
            model_name='alert',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
