# Generated by Django 5.0.7 on 2024-07-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_remove_alert_created_at_remove_alert_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
