# Generated by Django 5.0.7 on 2024-07-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alter_alert_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='symbol',
        ),
        migrations.AddField(
            model_name='alert',
            name='email',
            field=models.EmailField(default='irusnft@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alert',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
