# Generated by Django 5.0.7 on 2024-07-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alter_alert_price_alter_alert_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
